name = "etf-radar-proxy"
main = "workers/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "dummy-kv-id-for-local-dev-best-etf"
preview_id = "dummy-kv-preview-id-best-etf"

[triggers]
crons = ["10 9 * * MON-FRI", "10 10 * * MON-FRI"]
